#! /usr/bin/bash 

# DBMS initialization

if [  ! -d "~/Downloads/bash/project/DBMS" ]
then 
	mkdir -p ~/Downloads/bash/project/DBMS 
fi

cd ~/Downloads/bash/project/DBMS 
echo DBMS is running...

# CreateDatabase SelectDatabase CreateTable InsertTable 

select var in CreateDatabase SelectDatabase
do
	case $var in
	"CreateDatabase")
		read -p "Enter a new Database name: " DB_name
		if [[ -z $DB_name ]]
		then
			echo invalid DBname
		else
			if [ -e $DB_name ]
			then 
				echo $DB_name Database is already exist
			else
				mkdir $DB_name
				echo $DB_name Database is created successfully
			fi
		fi
		
	;;
	"SelectDatabase")
		read -p "Please Enter your Database name: " DB_name
		if [[ -z $DB_name ]]
		then
			echo invalid DBname
		else
			if [ -e $DB_name ]
			then 
				cd $DB_name
				echo Connected to database $DB_name
			else
				echo $DB_name Database doesn\'t exist
			fi
		fi
		
	;;
	*)
		echo invalid input
esac
done
