#! /usr/bin/bash 

# DBMS initialization

if [  ! -d "~/Downloads/bash/Bash-project/DBMS" ]
then 
	mkdir -p ~/Downloads/bash/Bash-project/DBMS 
fi

cd ~/Downloads/bash/Bash-project/DBMS 
echo DBMS is running...

source ~/Downloads/bash/Bash-project/database.sh